### ISSUE TITLE
Hummingbird probably doesn't reap zombies (dead orphaned processes)

### ISSUE THREAD

**Issue by aosync** [Sweets/hummingbird#14]
The solution to this is handling SIGCHLD then use `wait4((pid_t) -1, NULL, WNOHANG, NULL);` to reap any orphaned process when one gets killed.

**Comment by Sweets** [comment]
Given the usage of wait4() it would be more appropriate to use wait3() in your given solution. Neither wait3() nor wait4() will be used, because they are both non-standard. waitpid() is a better solution.

That being said, I'll implement reaping later today.

**Comment by dilyn-corner** [comment]
Is there any update on this?

**Comment by Sweets** [comment]
@dilyn-corner Yes, this was done quite some time ago, I just never pushed it. I'll push it as soon as I can.
