### ISSUE TITLE
Can not chroot into hummingbird based envoirment

### ISSUE THREAD

**Issue by Ocean-Moist** [Sweets/hummingbird#20]
I try to chroot, and it gives me:

```
Hummingbird must be ran as PID 1
```

It probably is an issue on my side, But this my be some weird thing with how hummingbird checks PID?

**Comment by Ocean-Moist** [comment]
I am going to say this is on me.

**Comment by Sweets** [comment]
Hummingbird checks pid with getpid(). Anything that isn’t 1 errors out (any non-1 PID means an init has already ran an presumably already done a boot up sequence).

https://github.com/Sweets/hummingbird/blob/master/src/hummingbird.c#L26
