### ISSUE TITLE
home directory not found

### ISSUE THREAD

**Issue by lieux** [Sweets/hummingbird#6]
OS: Arch Linux

I followed the instructions to the letter. However, upon logging in (I don't use a DM, just the tty), it shows the following:

-- _username_: /home/_username_: change directory failed: No such file or directory
Logging in with home = "/".

**Comment by Sweets** [comment]
Do you have /home on a separate partition? If so, is it mounted?

If not, you'll need to have it mounted in rc.init.local with `mount /dev/device /home`. If there's a particular order you need it mounted in (like directly after the kernel API for some reason), you can edit rc.init and mount it there.

**Comment by trvv** [comment]
~~edit rc.init.local please~~
